#!/bin/bash
# Evaluate one Stage-2 checkpoint against all held-out MD replicas.

#SBATCH --job-name=s2_mdref_eval
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:A100:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=120G
#SBATCH --time=04:00:00
#SBATCH --output=logs/slurm/stage2_mdref_eval_%j.out
#SBATCH --error=logs/slurm/stage2_mdref_eval_%j.err

set -euo pipefail
unset LD_PRELOAD
unset PROXYCHAINS_CONF_FILE
unset PROXYCHAINS_QUIET_MODE

ROOT="${ROOT:-/mnt/inaisfs/data/home/zhaozc_criait/XinxiangWang/BINDRAE}"
ENV_PREFIX=/mnt/inaisfs/data/home/zhaozc_criait/miniconda3/envs/BINDRAE
export PATH=/data/soft/slurm/24.11.4/bin:$ENV_PREFIX/bin:$PATH
export PYTHONUNBUFFERED=1
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"

cd "$ROOT"
mkdir -p logs/slurm logs/stage2/md_reference_eval
source /mnt/inaisfs/data/home/zhaozc_criait/miniconda3/etc/profile.d/conda.sh
conda activate BINDRAE

CHECKPOINT="${CHECKPOINT:?CHECKPOINT is required}"
MD_REFERENCE_CACHE_DIR="${MD_REFERENCE_CACHE_DIR:?MD_REFERENCE_CACHE_DIR is required}"
OUTPUT="${OUTPUT:?OUTPUT is required}"
SPLIT="${SPLIT:-train}"
VALID_SAMPLES_FILE="${VALID_SAMPLES_FILE:?VALID_SAMPLES_FILE is required}"
PATH_PARAMETERIZATION="${PATH_PARAMETERIZATION:-checkpoint}"
STAGE1V2_MODE="${STAGE1V2_MODE:-oracle_motion}"
STAGE1V2_CACHE_DIR="${STAGE1V2_CACHE_DIR:?STAGE1V2_CACHE_DIR is required}"
N_INTEGRATION_STEPS="${N_INTEGRATION_STEPS:-20}"
MAX_BATCHES="${MAX_BATCHES:-}"
MD_MIN_PHASE_CONFIDENCE="${MD_MIN_PHASE_CONFIDENCE:-0.05}"
PHASE_TAU_POSTPROCESS="${PHASE_TAU_POSTPROCESS:-none}"
PHASE_RESIDUAL_PEPTIDE_RETRACTION="${PHASE_RESIDUAL_PEPTIDE_RETRACTION:-checkpoint}"
PHASE_RESIDUAL_PEPTIDE_RETRACTION_ITERATIONS="${PHASE_RESIDUAL_PEPTIDE_RETRACTION_ITERATIONS:-8}"
PHASE_RESIDUAL_PEPTIDE_RETRACTION_RELAXATION="${PHASE_RESIDUAL_PEPTIDE_RETRACTION_RELAXATION:-0.75}"
PHASE_RESIDUAL_PEPTIDE_RETRACTION_ANCHOR_STRENGTH="${PHASE_RESIDUAL_PEPTIDE_RETRACTION_ANCHOR_STRENGTH:-0.02}"
PHASE_RESIDUAL_PEPTIDE_RETRACTION_MAX_TRANSLATION="${PHASE_RESIDUAL_PEPTIDE_RETRACTION_MAX_TRANSLATION:-1.0}"
PHASE_RESIDUAL_PEPTIDE_RETRACTION_ACTIVATION_LOSS_THRESHOLD="${PHASE_RESIDUAL_PEPTIDE_RETRACTION_ACTIVATION_LOSS_THRESHOLD:-0.0}"
PHYSICAL_NORMAL_ITERATIONS="${PHYSICAL_NORMAL_ITERATIONS:-8}"
PHYSICAL_NORMAL_LEARNING_RATE="${PHYSICAL_NORMAL_LEARNING_RATE:-0.05}"
PHYSICAL_NORMAL_ENVELOPE="${PHYSICAL_NORMAL_ENVELOPE:-poly}"
PHYSICAL_NORMAL_PROJECTION_MODE="${PHYSICAL_NORMAL_PROJECTION_MODE:-block}"
PHYSICAL_NORMAL_COMPONENTS="${PHYSICAL_NORMAL_COMPONENTS:-translation}"
PHYSICAL_NORMAL_MAX_METRIC_NORM="${PHYSICAL_NORMAL_MAX_METRIC_NORM:-1.0}"
PHYSICAL_NORMAL_GRADIENT_CLIP="${PHYSICAL_NORMAL_GRADIENT_CLIP:-10.0}"
PHYSICAL_NORMAL_PROTEIN_CLASH_DIST="${PHYSICAL_NORMAL_PROTEIN_CLASH_DIST:-2.0}"
PHYSICAL_NORMAL_LIGAND_CLASH_DIST="${PHYSICAL_NORMAL_LIGAND_CLASH_DIST:-2.2}"
PHYSICAL_NORMAL_MAX_CLASH_ATOMS="${PHYSICAL_NORMAL_MAX_CLASH_ATOMS:-256}"
PHYSICAL_NORMAL_WEIGHT_PEPTIDE="${PHYSICAL_NORMAL_WEIGHT_PEPTIDE:-1.0}"
PHYSICAL_NORMAL_WEIGHT_PROTEIN_CLASH="${PHYSICAL_NORMAL_WEIGHT_PROTEIN_CLASH:-1.0}"
PHYSICAL_NORMAL_WEIGHT_LIGAND_CLASH="${PHYSICAL_NORMAL_WEIGHT_LIGAND_CLASH:-1.0}"
PHYSICAL_NORMAL_WEIGHT_CONTACT_ANCHOR="${PHYSICAL_NORMAL_WEIGHT_CONTACT_ANCHOR:-0.25}"
PHYSICAL_NORMAL_WEIGHT_DISTANCE_ANCHOR="${PHYSICAL_NORMAL_WEIGHT_DISTANCE_ANCHOR:-1.0}"
PHYSICAL_NORMAL_WEIGHT_RESIDUAL="${PHYSICAL_NORMAL_WEIGHT_RESIDUAL:-0.1}"
PHYSICAL_NORMAL_WEIGHT_TEMPORAL="${PHYSICAL_NORMAL_WEIGHT_TEMPORAL:-0.2}"
PHYSICAL_NORMAL_OPTIMIZER="${PHYSICAL_NORMAL_OPTIMIZER:-adam}"
PHYSICAL_NORMAL_NUM_STARTS="${PHYSICAL_NORMAL_NUM_STARTS:-1}"
PHYSICAL_NORMAL_ROUTE_SEED_SCALE="${PHYSICAL_NORMAL_ROUTE_SEED_SCALE:-0.0}"
PHYSICAL_NORMAL_ROUTE_SEED_RANK="${PHYSICAL_NORMAL_ROUTE_SEED_RANK:-2}"
PHYSICAL_NORMAL_ROUTE_SEED_SMOOTHING_STEPS="${PHYSICAL_NORMAL_ROUTE_SEED_SMOOTHING_STEPS:-2}"
PHYSICAL_NORMAL_ROUTE_SEED="${PHYSICAL_NORMAL_ROUTE_SEED:-20260720}"
PHYSICAL_NORMAL_FRAME_AGGREGATION="${PHYSICAL_NORMAL_FRAME_AGGREGATION:-mean}"
PHYSICAL_NORMAL_FRAME_SOFTMAX_BETA="${PHYSICAL_NORMAL_FRAME_SOFTMAX_BETA:-10.0}"
PHYSICAL_NORMAL_LINE_SEARCH_STEPS="${PHYSICAL_NORMAL_LINE_SEARCH_STEPS:-8}"
PHYSICAL_NORMAL_LINE_SEARCH_SHRINK="${PHYSICAL_NORMAL_LINE_SEARCH_SHRINK:-0.5}"
PHYSICAL_NORMAL_ACCEPTANCE_TOLERANCE="${PHYSICAL_NORMAL_ACCEPTANCE_TOLERANCE:-1e-8}"

ARGS=(
  --checkpoint "$CHECKPOINT"
  --data_dir processed_data/triplets
  --split "$SPLIT"
  --valid_samples_file "$VALID_SAMPLES_FILE"
  --trust_prechecked_samples
  --batch_size 1
  --num_workers 0
  --path_parameterization "$PATH_PARAMETERIZATION"
  --stage1v2_posterior_feature_mode "$STAGE1V2_MODE"
  --stage1v2_posterior_cache_dir "$STAGE1V2_CACHE_DIR"
  --n_integration_steps "$N_INTEGRATION_STEPS"
  --md_reference_cache_dir "$MD_REFERENCE_CACHE_DIR"
  --md_min_phase_confidence "$MD_MIN_PHASE_CONFIDENCE"
  --phase_tau_postprocess "$PHASE_TAU_POSTPROCESS"
  --phase_residual_peptide_retraction_iterations "$PHASE_RESIDUAL_PEPTIDE_RETRACTION_ITERATIONS"
  --phase_residual_peptide_retraction_relaxation "$PHASE_RESIDUAL_PEPTIDE_RETRACTION_RELAXATION"
  --phase_residual_peptide_retraction_anchor_strength "$PHASE_RESIDUAL_PEPTIDE_RETRACTION_ANCHOR_STRENGTH"
  --phase_residual_peptide_retraction_max_translation "$PHASE_RESIDUAL_PEPTIDE_RETRACTION_MAX_TRANSLATION"
  --phase_residual_peptide_retraction_activation_loss_threshold "$PHASE_RESIDUAL_PEPTIDE_RETRACTION_ACTIVATION_LOSS_THRESHOLD"
  --physical_normal_iterations "$PHYSICAL_NORMAL_ITERATIONS"
  --physical_normal_learning_rate "$PHYSICAL_NORMAL_LEARNING_RATE"
  --physical_normal_envelope "$PHYSICAL_NORMAL_ENVELOPE"
  --physical_normal_projection_mode "$PHYSICAL_NORMAL_PROJECTION_MODE"
  --physical_normal_components "$PHYSICAL_NORMAL_COMPONENTS"
  --physical_normal_max_metric_norm "$PHYSICAL_NORMAL_MAX_METRIC_NORM"
  --physical_normal_gradient_clip "$PHYSICAL_NORMAL_GRADIENT_CLIP"
  --physical_normal_protein_clash_dist "$PHYSICAL_NORMAL_PROTEIN_CLASH_DIST"
  --physical_normal_ligand_clash_dist "$PHYSICAL_NORMAL_LIGAND_CLASH_DIST"
  --physical_normal_max_clash_atoms "$PHYSICAL_NORMAL_MAX_CLASH_ATOMS"
  --physical_normal_weight_peptide "$PHYSICAL_NORMAL_WEIGHT_PEPTIDE"
  --physical_normal_weight_protein_clash "$PHYSICAL_NORMAL_WEIGHT_PROTEIN_CLASH"
  --physical_normal_weight_ligand_clash "$PHYSICAL_NORMAL_WEIGHT_LIGAND_CLASH"
  --physical_normal_weight_contact_anchor "$PHYSICAL_NORMAL_WEIGHT_CONTACT_ANCHOR"
  --physical_normal_weight_distance_anchor "$PHYSICAL_NORMAL_WEIGHT_DISTANCE_ANCHOR"
  --physical_normal_weight_residual "$PHYSICAL_NORMAL_WEIGHT_RESIDUAL"
  --physical_normal_weight_temporal "$PHYSICAL_NORMAL_WEIGHT_TEMPORAL"
  --physical_normal_optimizer "$PHYSICAL_NORMAL_OPTIMIZER"
  --physical_normal_num_starts "$PHYSICAL_NORMAL_NUM_STARTS"
  --physical_normal_route_seed_scale "$PHYSICAL_NORMAL_ROUTE_SEED_SCALE"
  --physical_normal_route_seed_rank "$PHYSICAL_NORMAL_ROUTE_SEED_RANK"
  --physical_normal_route_seed_smoothing_steps "$PHYSICAL_NORMAL_ROUTE_SEED_SMOOTHING_STEPS"
  --physical_normal_route_seed "$PHYSICAL_NORMAL_ROUTE_SEED"
  --physical_normal_frame_aggregation "$PHYSICAL_NORMAL_FRAME_AGGREGATION"
  --physical_normal_frame_softmax_beta "$PHYSICAL_NORMAL_FRAME_SOFTMAX_BETA"
  --physical_normal_line_search_steps "$PHYSICAL_NORMAL_LINE_SEARCH_STEPS"
  --physical_normal_line_search_shrink "$PHYSICAL_NORMAL_LINE_SEARCH_SHRINK"
  --physical_normal_acceptance_tolerance "$PHYSICAL_NORMAL_ACCEPTANCE_TOLERANCE"
  --device cuda
  --output "$OUTPUT"
)
case "$PHASE_RESIDUAL_PEPTIDE_RETRACTION" in
  checkpoint) ;;
  on) ARGS+=(--phase_residual_peptide_retraction) ;;
  off) ARGS+=(--no_phase_residual_peptide_retraction) ;;
  *)
    echo "ERROR: PHASE_RESIDUAL_PEPTIDE_RETRACTION must be checkpoint, on, or off"
    exit 1
    ;;
esac
if [[ -n "$MAX_BATCHES" ]]; then
  ARGS+=(--max_batches "$MAX_BATCHES")
fi

echo "Checkpoint:    $CHECKPOINT"
echo "Path mode:     $PATH_PARAMETERIZATION"
echo "MD references: $MD_REFERENCE_CACHE_DIR"
echo "Samples:       $VALID_SAMPLES_FILE"
echo "Path steps:    $N_INTEGRATION_STEPS"
echo "Physical iter: $PHYSICAL_NORMAL_ITERATIONS"
echo "Physical proj: $PHYSICAL_NORMAL_PROJECTION_MODE"
echo "Physical comp: $PHYSICAL_NORMAL_COMPONENTS"
echo "Physical optimizer: $PHYSICAL_NORMAL_OPTIMIZER"
echo "Physical starts: $PHYSICAL_NORMAL_NUM_STARTS"
echo "Physical seed scale: $PHYSICAL_NORMAL_ROUTE_SEED_SCALE"
echo "Physical frame agg: $PHYSICAL_NORMAL_FRAME_AGGREGATION"
echo "Tau postproc:  $PHASE_TAU_POSTPROCESS"
echo "Peptide retract: $PHASE_RESIDUAL_PEPTIDE_RETRACTION"
echo "Output:        $OUTPUT"
echo "Start:         $(date)"

python scripts/evaluate_stage2_md_reference_paths.py "${ARGS[@]}"

echo "Completed: $(date)"
echo "Output:    $OUTPUT"
