#!/bin/bash
# Screen multi-start projected normal refinement on a frozen Path-3 checkpoint.
# This uses differentiable geometry/clash surrogates; it is not the final
# OpenMM Gate-0 physical validation.

#SBATCH --job-name=p4opt_screen
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:A100:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=120G
#SBATCH --time=04:00:00
#SBATCH --output=logs/slurm/path4_multistart_screen_%j.out
#SBATCH --error=logs/slurm/path4_multistart_screen_%j.err

set -euo pipefail

ROOT="${ROOT:-/mnt/inaisfs/data/home/zhaozc_criait/XinxiangWang/BINDRAE}"
CHECKPOINT="${CHECKPOINT:?CHECKPOINT is required}"
VALID_SAMPLES_FILE="${VALID_SAMPLES_FILE:?VALID_SAMPLES_FILE is required}"
STAGE1V2_CACHE_DIR="${STAGE1V2_CACHE_DIR:?STAGE1V2_CACHE_DIR is required}"

export ROOT CHECKPOINT VALID_SAMPLES_FILE STAGE1V2_CACHE_DIR
export TAG="${TAG:-path4_multistart_screen_${SLURM_JOB_ID:-manual}}"
export SPLIT="${SPLIT:-train}"
export TRUST_PRECHECKED_SAMPLES="${TRUST_PRECHECKED_SAMPLES:-1}"
export STAGE1V2_MODE="${STAGE1V2_MODE:-oracle_motion}"
export PATH_PARAMETERIZATION=phase_physical_normal_v1
export PHASE_TAU_POSTPROCESS="${PHASE_TAU_POSTPROCESS:-cummax}"
export BATCH_SIZE=1
export MAX_BATCHES="${MAX_BATCHES:-8}"
export N_INTEGRATION_STEPS="${N_INTEGRATION_STEPS:-20}"
export INCLUDE_PER_SAMPLE_METRICS="${INCLUDE_PER_SAMPLE_METRICS:-1}"

export PHYSICAL_NORMAL_OPTIMIZER="${PHYSICAL_NORMAL_OPTIMIZER:-backtracking}"
export PHYSICAL_NORMAL_NUM_STARTS="${PHYSICAL_NORMAL_NUM_STARTS:-8}"
export PHYSICAL_NORMAL_ROUTE_SEED_SCALE="${PHYSICAL_NORMAL_ROUTE_SEED_SCALE:-0.25}"
export PHYSICAL_NORMAL_ROUTE_SEED_RANK="${PHYSICAL_NORMAL_ROUTE_SEED_RANK:-2}"
export PHYSICAL_NORMAL_ROUTE_SEED_SMOOTHING_STEPS="${PHYSICAL_NORMAL_ROUTE_SEED_SMOOTHING_STEPS:-2}"
export PHYSICAL_NORMAL_ROUTE_SEED="${PHYSICAL_NORMAL_ROUTE_SEED:-20260720}"
export PHYSICAL_NORMAL_ITERATIONS="${PHYSICAL_NORMAL_ITERATIONS:-12}"
export PHYSICAL_NORMAL_LEARNING_RATE="${PHYSICAL_NORMAL_LEARNING_RATE:-0.05}"
export PHYSICAL_NORMAL_FRAME_AGGREGATION="${PHYSICAL_NORMAL_FRAME_AGGREGATION:-softmax}"
export PHYSICAL_NORMAL_FRAME_SOFTMAX_BETA="${PHYSICAL_NORMAL_FRAME_SOFTMAX_BETA:-10.0}"
export PHYSICAL_NORMAL_LINE_SEARCH_STEPS="${PHYSICAL_NORMAL_LINE_SEARCH_STEPS:-8}"
export PHYSICAL_NORMAL_LINE_SEARCH_SHRINK="${PHYSICAL_NORMAL_LINE_SEARCH_SHRINK:-0.5}"
export PHYSICAL_NORMAL_ACCEPTANCE_TOLERANCE="${PHYSICAL_NORMAL_ACCEPTANCE_TOLERANCE:-1e-8}"
export PHYSICAL_NORMAL_MAX_METRIC_NORM="${PHYSICAL_NORMAL_MAX_METRIC_NORM:-1.0}"
export PHYSICAL_NORMAL_WEIGHT_RESIDUAL="${PHYSICAL_NORMAL_WEIGHT_RESIDUAL:-0.2}"
export PHYSICAL_NORMAL_WEIGHT_TEMPORAL="${PHYSICAL_NORMAL_WEIGHT_TEMPORAL:-0.2}"
export OUTPUT="${OUTPUT:-logs/stage2/transition_eval/${TAG}.json}"

cd "$ROOT"
exec bash scripts/slurm/evaluate_stage2_transition_paths_1gpu.sh
